# Continuação da Análise Exploratória de Dados

<div class="alert alert-info">
    <b>AVISO</b>
    <details>
        <summary>
            <font style='font-size:16px color:black;'>
                <b>São clicaveis</b>
            </font>
        </summary>
    <ul>
        <li>Guardam informação</li>
    </ul>
    </details>
    
</div>

In [10]:
import pandas as pd

df = pd.read_csv("acidentes2018.csv",encoding='latin_1',sep=';')
df

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,100027.0,217755,2018-01-01,segunda-feira,06:00:00,TO,153,"393,1",RIO DOS BOIS,Falta de Atenção à Condução,...,Masculino,1,0,0,0,"-9,35641407","-48,54610294",SPRF-TO,DEL02-TO,UOP02-DEL02-TO
1,100044.0,223725,2018-01-01,segunda-feira,08:30:00,SE,101,"123,4",ITAPORANGA DAJUDA,Não guardar distância de segurança,...,Masculino,1,0,0,0,"-11,04476007","-37,36498",SPRF-SE,DEL02-SE,UOP01-DEL02-SE
2,100044.0,223727,2018-01-01,segunda-feira,08:30:00,SE,101,"123,4",ITAPORANGA DAJUDA,Não guardar distância de segurança,...,Masculino,1,0,0,0,"-11,04476007","-37,36498",SPRF-SE,DEL02-SE,UOP01-DEL02-SE
3,100046.0,216424,2018-01-01,segunda-feira,08:50:00,TO,153,347,GUARAI,Falta de Atenção à Condução,...,Masculino,1,0,0,0,"-8,952295","-48,500107",SPRF-TO,DEL02-TO,UOP02-DEL02-TO
4,100052.0,216587,2018-01-01,segunda-feira,05:30:00,PA,155,221,ELDORADO DO CARAJAS,Ingestão de Álcool,...,Masculino,1,0,0,0,"-6,345512","-49,389626",SPRF-PA,DEL03-PA,UOP01-DEL03-PA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180056,593091.0,1321335,2018-11-11,domingo,00:50:00,PR,369,"45,8",BANDEIRANTES,Ingestão de álcool pelo condutor,...,Masculino,0,1,0,0,"-23,09035157","-50,29617894",SPRF-PR,DEL07-PR,UOP05-DEL07-PR
180057,593091.0,1321333,2018-11-11,domingo,00:50:00,PR,369,"45,8",BANDEIRANTES,Ingestão de álcool pelo condutor,...,Masculino,1,0,0,0,"-23,09035157","-50,29617894",SPRF-PR,DEL07-PR,UOP05-DEL07-PR
180058,593091.0,1321334,2018-11-11,domingo,00:50:00,PR,369,"45,8",BANDEIRANTES,Ingestão de álcool pelo condutor,...,Masculino,0,1,0,0,"-23,09035157","-50,29617894",SPRF-PR,DEL07-PR,UOP05-DEL07-PR
180059,594880.0,1325466,2018-05-31,quinta-feira,23:30:00,MG,40,"282,1",TRES MARIAS,Ingestão de álcool pelo condutor,...,Masculino,0,0,1,0,"-18,249315","-45,202118",SPRF-MG,DEL14-MG,UOP02-DEL14-MG
180060,594880.0,1325467,2018-05-31,quinta-feira,23:30:00,MG,40,"282,1",TRES MARIAS,Ingestão de álcool pelo condutor,...,Masculino,0,1,0,0,"-18,249315","-45,202118",SPRF-MG,DEL14-MG,UOP02-DEL14-MG

In [11]:
primeiro_registro = df.iloc[0].to_dict()   
primeiro_registro

{'id': 100027.0,
 'pesid': 217755,
 'data_inversa': '2018-01-01',
 'dia_semana': 'segunda-feira',
 'horario': '06:00:00',
 'uf': 'TO',
 'br': 153,
 'km': '393,1',
 'municipio': 'RIO DOS BOIS',
 'causa_acidente': 'Falta de Atenção à Condução',
 'tipo_acidente': 'Colisão frontal',
 'classificacao_acidente': 'Com Vítimas Feridas',
 'fase_dia': 'Pleno dia',
 'sentido_via': 'Decrescente',
 'condicao_metereologica': 'Céu Claro',
 'tipo_pista': 'Simples',
 'tracado_via': 'Aclive',
 'uso_solo': 'Não',
 'id_veiculo': 177729,
 'tipo_veiculo': 'Caminhão',
 'marca': 'FORD/CARGO 1729',
 'ano_fabricacao_veiculo': 2013,
 'tipo_envolvido': 'Condutor',
 'estado_fisico': 'Ileso',
 'idade': 52,
 'sexo': 'Masculino',
 'ilesos': 1,
 'feridos_leves': 0,
 'feridos_graves': 0,
 'mortos': 0,
 'latitude': '-9,35641407',
 'longitude': '-48,54610294',
 'regional': 'SPRF-TO',
 'delegacia': 'DEL02-TO',
 'uop': 'UOP02-DEL02-TO'}

<div>
    <b>
        <font style='font-size: 64px;color: #88E788'>
            Tarefa 1
        </font>
    </b>
</div>

<details>
    <summary>
        <font style='font-size:20px;color: #ffffff;'>
            <b>Classificação das Variáveis</b>
        </font>
    </summary>

1. <b>dia_semana</b>
    - Tipo: Qualitativa Nominal
    - São categorias (segunda, terça, etc.). ela não representa hierarquia (terça não é   “maior” que segunda).
    - No DataFrame, aparece como string.
2. <b>fase_dia</b>
    - Tipo: Qualitativa Ordinal
    - Existe uma ordem baseada no momento do dia (Pleno dia, Anoitecer, Plena noite).
    - Também aparece como string.
3. <b>idade</b>
    - Tipo: Quantitativa Discreta
    - Idade normalmente é contada em inteiros. Logo é discreta.
    - são classificados como int
4. <b>tipo_veiculo</b>
    - Tipo: Qualitativa Nominal
    - São descritos os nomes dos veiculos.
    - Também aparece como string.
</details>

<table>
    <tr>
        <td><b>Váriavel</b></td>
        <td><b>Tipo</b></td>
    </tr>
    <tr>
        <td>dia_semana</td>
        <td>Qualitativa Nominal</td>
    </tr>
    <tr>
        <td>fase_dia</td>
        <td>Qualitativa Ordinal</td>
    </tr>
    <tr>
        <td>idade</td>
        <td>Quantitativa Discreta</td>
    </tr>
    <tr>
        <td>tipo_veiculo</td>
        <td>Qualitativa Nominal</td>
    </tr>
</table>

<div>
    <b>
        <font style='font-size: 64px;color: #88E788'>
            Tarefa 2
        </font>
    </b>
</div>

<details>
    <summary>
        <font style='font-size: 20px;color: #ffffff'>
            <b>Encoding (fase_dia)</b>
        </font>
    </summary>

* Plena noite → 0
* Anoitecer → 1
* Amanhecer → 2
* Pleno dia → 3
</details>

In [ ]:
import pandas as pd

# Criando um mapeamento de cada string para se tornar int

mapping = {
    "Plena Noite": 0,
    "Anoitecer": 1,
    "Amanhecer": 2,
    "Pleno dia": 3
}

# Criando uma coluna codificada

df["fase_dia_encoded"] = df["fase_dia"].map(mapping)
df["fase_dia_encoded"].head()

0    3
1    3
2    3
3    3
4    2
Name: fase_dia_encoded, dtype: int64

In [ ]:
# Verificando se existe alguma string não mapeada

df[df["fase_dia"].map(mapping).isna()]["fase_dia"].unique()

array([], dtype=object)

<div>
    <b>
        <font style='font-size: 64px;color: #88E788'>
            Tarefa 3
        </font>
    </b>
</div>

<table>
    <tr>
        <td><b>Bins</b></td>
        <td><b>Labels</b></td>
    </tr>
    <tr>
        <td>[0, 18]</td>
        <td>Menores de idade</td>
    </tr>
    <tr>
        <td>[18, 30]</td>
        <td>Jovens</td>
    </tr>
    <tr>
        <td>[30, 60]</td>
        <td>Adultos</td>
    </tr>
    <tr>
        <td>[60, 120]</td>
        <td>Idosos</td>
    </tr>
</table>

<details>
    <summary>
        <font style='font-size:20px;color: #ffffff'>
            <b>Binning (faixa_etaria)</b>
        </font> 
    </summary>

- Transforma variável numérica em qualitativa ordinal
- Ajuda a identificar perfis demográficos
</details>

In [ ]:
import pandas as pd

bins = [0, 18, 30, 60, 120]
labels = ["Menores de idade", "Jovens", "Adultos", "Idosos"]

df["faixa_etaria"] = pd.cut(df["idade"], bins=bins, labels=labels, right=False)
df["faixa_etaria"]

0                  Adultos
1                   Idosos
2         Menores de idade
3                   Idosos
4                   Idosos
                ...
180056              Jovens
180057             Adultos
180058              Jovens
180059             Adultos
180060              Idosos
Name: faixa_etaria, Length: 180061, dtype: category
Categories (4, object): ['Menores de idade' < 'Jovens' < 'Adultos' < 'Idosos']

<div>
    <b>
        <font style='font-size: 64px;color: #88E788'>
            Tarefa 4
        </font>
    </b>
</div>

<div>
    <b>
        <font style='font-size: 24px;color: #87ecfd'>
            Criando um novo dataframe com base na coluna "faixa_etaria".
        </font>
    </b>
</div>

In [54]:
import pandas as pd

df_freq = df["faixa_etaria"].value_counts().reset_index()
df_freq.columns = ["faixa_etaria", "fi"]
df_freq

       faixa_etaria     fi
0           Adultos  88889
1            Jovens  38735
2  Menores de idade  38180
3            Idosos  13945

<div>
    <b>
        <font style='font-size: 24px;color: #87ecfd'>
            Ordenando as categórias do dataframe
        </font>
    </b>
</div>

In [55]:
ordem = ["Menores de idade", "Jovens", "Adultos", "Idosos"]

df_freq["faixa_etaria"] = pd.Categorical(df_freq["faixa_etaria"], categories=ordem, ordered=True)
df_freq = df_freq.sort_values("faixa_etaria").reset_index(drop=True)
df_freq

       faixa_etaria     fi
0  Menores de idade  38180
1            Jovens  38735
2           Adultos  88889
3            Idosos  13945

<div>
    <b>
        <font style='font-size: 24px;color: #87ecfd'>
            Definindo a coluna acumulativa do dataframe.
        </font>
    </b>
</div>

In [56]:
df_freq["Fi"] = df_freq["fi"].cumsum()
df_freq

       faixa_etaria     fi      Fi
0  Menores de idade  38180   38180
1            Jovens  38735   76915
2           Adultos  88889  165804
3            Idosos  13945  179749

<div>
    <b>
        <font style='font-size: 24px;color: #87ecfd'>
            Definindo as colunas de porcentagem do dataframe.
        </font>
    </b>
</div>

In [57]:
total = df_freq["fi"].sum()

df_freq["fr (%)"] = (df_freq["fi"]/total) *100
df_freq["Fr (%)"] = df_freq["fr (%)"].cumsum()

df_freq

       faixa_etaria     fi      Fi     fr (%)      Fr (%)
0  Menores de idade  38180   38180  21.240730   21.240730
1            Jovens  38735   76915  21.549494   42.790224
2           Adultos  88889  165804  49.451735   92.241960
3            Idosos  13945  179749   7.758040  100.000000

<div>
    <b>
        <font style='font-size: 24px;color: #87ecfd'>
            Arredondando o números quebrados da divisão. Além disso transformando em string para poder adicionar o "%"
        </font>
    </b>
</div>

In [58]:
df_freq["fr (%)"] = df_freq["fr (%)"].round(0).astype(str) + "%"
df_freq["Fr (%)"] = df_freq["Fr (%)"].round(0).astype(str) + "%"

df_freq

       faixa_etaria     fi      Fi fr (%)  Fr (%)
0  Menores de idade  38180   38180  21.0%   21.0%
1            Jovens  38735   76915  22.0%   43.0%
2           Adultos  88889  165804  49.0%   92.0%
3            Idosos  13945  179749   8.0%  100.0%

In [59]:
linha_nova = {"faixa_etaria": "total","fi": total,"fr (%)":"100%"}
df_freq.loc[len(df_freq)] = linha_nova
df_freq

       faixa_etaria      fi        Fi fr (%)  Fr (%)
0  Menores de idade   38180   38180.0  21.0%   21.0%
1            Jovens   38735   76915.0  22.0%   43.0%
2           Adultos   88889  165804.0  49.0%   92.0%
3            Idosos   13945  179749.0   8.0%  100.0%
4             total  179749       NaN   100%     NaN

<div>
    <b>
        <font style='font-size: 64px;color: #88E788'>
            Tarefa 4.b
        </font>
    </b>
</div>

A distribuição mostra que a maior parte das vítimas está concentrada entre jovens e adultos, especialmente adultos, que representam o grupo mais exposto. Além disso, a frequência acumulada revela que **90% das vítimas têm menos de 60 anos**, indicando que os adultos estão mais expostos devido a rotina de trabalho.

<div>
    
Essa informação pode ser usada pela PRF para:

- direcionar campanhas educativas,
- intensificar fiscalização em horários de trabalho,
- focar em motoristas ativos
</div>