# Análise Exploratória de Dados

### Baixando arquivos.

In [ ]:
!apt-get install -y megatools
!mkdir infracoes

!megadl "https://mega.nz/file/96wmRJRD#WPmLGUJYa84aYR3Qrnrko7zthxGuRL5VuuwK1g62jwI" \
  --path /content/infracoes/infracoes_2018.zip

!megadl "https://mega.nz/file/k3RS1JwZ#jf0hnP6Jy9K9SzH1_vyS-BaQlMF4vO5n2G-a6Ge0vvI" \
  --path /content/infracoes/infracoes_2021.zip

!megadl "https://mega.nz/file/1nwTSTBC#OHmSACYGagRV2ZMAl7F9ktTu5PX3uUbpC_-47VgRcSo" \
  --path /content/infracoes/infracoes_2025.zip

print("\033[32mDownload finalizado!\033[m")

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  megatools
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 207 kB of archives.
After this operation, 898 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 megatools amd64 1.10.3-1build1 [207 kB]
Fetched 207 kB in 1s (343 kB/s)
Selecting previously unselected package megatools.
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../megatools_1.10.3-1build1_amd64.deb ...
Unpacking megatools (1.10.3-1build1) ...
Setting up megatools (1.10.3-1build1) ...
Processing triggers for man-db (2.10.2-1) ...
Downloaded infracoes_2018.zip
Downloaded infrações_2021.zip
Downloaded infrações_2025.zip
Download finalizado!

In [ ]:
!mkdir acidentes

!megadl "https://mega.nz/file/VnIG0SgI#7RX1owbScp7IgRU06UwvsKZUpkZyDstV73G7jKYf6nY" \
  --path /content/acidentes/acidentes_2018.zip

!megadl "https://mega.nz/file/1mgwwAKL#0ff5c_m-SUtZJhRGSn_PTSW23HyJ3hhGtXq3s9Hat6w" \
  --path /content/acidentes/acidentes_2021.zip

!megadl "https://mega.nz/file/AioT2QwY#UDcswOFWQPvxAL5eiOy8xusiHD9fZmAwlfIuip2eP7M" \
  --path /content/acidentes/acidentes_2025.zip

print("\033[32mDownload finalizado!\033[m")

Downloaded datatran2018.zip
Downloaded datatran2021.zip
Downloaded datatran2025.zip
Download finalizado!

### Tirando do zip

In [ ]:
import os
import zipfile

pastas = [
    "infracoes_2018", "infracoes_2021","infracoes_2025"
]

for pasta in pastas:
    caminho_pasta = f"/content/infracoes/{pasta}"
    arquivo_zip = f"/content/infracoes/{pasta}.zip"

    os.makedirs(caminho_pasta, exist_ok=True)

    with zipfile.ZipFile(arquivo_zip, "r") as dataset:
        dataset.extractall(caminho_pasta)

### Apagando pasta criada e movendo o .csv

In [ ]:
import shutil
import os

pastas = [
    "infracoes_2018", "infracoes_2021", "infracoes_2025"
]

for pasta in pastas:
  pasta_raiz = f"/content/infracoes/{pasta}"
  # Verifica se há uma subpasta na pasta atual
  subdir = [name for name in os.listdir(pasta_raiz) if os.path.isdir(os.path.join(pasta_raiz, name))]
  if subdir:
    subpasta = f"{pasta_raiz}/{subdir[0]}"
    for arquivo in os.listdir(subpasta):
      if arquivo.endswith(".csv"):
        origem = os.path.join(subpasta, arquivo)
        destino = os.path.join(pasta_raiz, arquivo)
        shutil.move(origem, destino)
    # Remove a subpasta
    shutil.rmtree(subpasta)

## Infrações

### Juntando meses de  infrações.

In [2]:
import pandas as pd
import shutil
import os

# Localizando pasta
lista_infracoes = []
pastas = [
    "infracoes_2018", "infracoes_2021", "infracoes_2025"
]


for dir in pastas:
  for raiz, pasta, arquivo in os.walk(f"/content/infracoes/{dir}"):
    if arquivo:
      lista_infracoes.append(sorted(arquivo))

aux = 0
lista_infracoes_2018 = []
lista_infracoes_2021 = []
lista_infracoes_2025 = []

# Colocando em listas

for infracao in lista_infracoes:
  for ordem, arquivo in enumerate(infracao):
    if aux<12:
      temp = pd.read_csv(f"/content/infracoes/infracoes_2018/{arquivo}",encoding="latin_1", sep=",")
      lista_infracoes_2018.append(temp)
      print(f"\033[34mDataframe {ordem+1} de 2018 lido!\033[m")
    elif 12<=aux<24:
      temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")
      lista_infracoes_2021.append(temp)
      print(f"\033[34mDataframe {ordem+1} de 2021 lido!\033[m")
    elif 24<=aux:
      temp = pd.read_csv(f"/content/infracoes/infracoes_2025/{arquivo}",encoding="latin_1", sep=";")
      lista_infracoes_2025.append(temp)
      print(f"\033[34mDataframe {ordem+1} de 2025 lido!\033[m")
    aux +=1




lista_infracoes_2018 = pd.concat(lista_infracoes_2018)
lista_infracoes_2021 = pd.concat(lista_infracoes_2021)
lista_infracoes_2025 = pd.concat(lista_infracoes_2025)

/tmp/ipykernel_63166/1819238999.py:27: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2018/{arquivo}",encoding="latin_1", sep=",")

Dataframe 1 de 2018 lido!

/tmp/ipykernel_63166/1819238999.py:27: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2018/{arquivo}",encoding="latin_1", sep=",")

Dataframe 2 de 2018 lido!

/tmp/ipykernel_63166/1819238999.py:27: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2018/{arquivo}",encoding="latin_1", sep=",")

Dataframe 3 de 2018 lido!

/tmp/ipykernel_63166/1819238999.py:27: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2018/{arquivo}",encoding="latin_1", sep=",")

Dataframe 4 de 2018 lido!

/tmp/ipykernel_63166/1819238999.py:27: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2018/{arquivo}",encoding="latin_1", sep=",")

Dataframe 5 de 2018 lido!
Dataframe 6 de 2018 lido!
Dataframe 7 de 2018 lido!
Dataframe 8 de 2018 lido!
Dataframe 9 de 2018 lido!
Dataframe 10 de 2018 lido!
Dataframe 11 de 2018 lido!
Dataframe 12 de 2018 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 1 de 2021 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 2 de 2021 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 3 de 2021 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 4 de 2021 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 5 de 2021 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 6 de 2021 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 7 de 2021 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 8 de 2021 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 9 de 2021 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 10 de 2021 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 11 de 2021 lido!

/tmp/ipykernel_63166/1819238999.py:31: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  temp = pd.read_csv(f"/content/infracoes/infracoes_2021/{arquivo}",encoding="latin_1", sep=";")

Dataframe 12 de 2021 lido!
Dataframe 1 de 2025 lido!
Dataframe 2 de 2025 lido!
Dataframe 3 de 2025 lido!
Dataframe 4 de 2025 lido!
Dataframe 5 de 2025 lido!
Dataframe 6 de 2025 lido!
Dataframe 7 de 2025 lido!
Dataframe 8 de 2025 lido!
Dataframe 9 de 2025 lido!
Dataframe 10 de 2025 lido!
Dataframe 11 de 2025 lido!
Dataframe 12 de 2025 lido!

### Conferindo Variáveis

In [4]:
anos_infracoes = [
    lista_infracoes_2018,lista_infracoes_2021,lista_infracoes_2025
    ]
anos = [2018,2021,2025]

for ordem,ano in enumerate(anos_infracoes):
  print(f"================{anos[ordem]}================")
  ano.info()

================2018================
<class 'pandas.core.frame.DataFrame'>
Index: 7356159 entries, 0 to 727724
Data columns (total 22 columns):
 #   Column                   Dtype
---  ------                   -----
 0   dat_infracao             object
 1   tip_abordagem            object
 2   ind_assinou_auto         object
 3   ind_veiculo_estrangeiro  object
 4   ind_sentido_trafego      object
 5   uf_placa                 object
 6   uf_infracao              object
 7   num_br_infracao          int64
 8   num_km_infracao          int64
 9   nom_municipio            object
 10  cod_infracao             int64
 11  descricao_abreviada      object
 12  enquadramento            object
 13  data_inicio_vigencia     object
 14  data_fim_vigencia        object
 15  med_realizada            float64
 16  med_considerada          float64
 17  exc_verificado           float64
 18  especie                  object
 19  nome_veiculo_marca       object
 20  nom_modelo_veiculo       object
 21  hora                     object
dtypes: float64(3), int64(3), object(16)
memory usage: 1.3+ GB
================2021================
<class 'pandas.core.frame.DataFrame'>
Index: 5241299 entries, 0 to 414770
Data columns (total 22 columns):
 #   Column                         Dtype
---  ------                         -----
 0   Número do Auto                 object
 1   Data da Infração (DD/MM/AAAA)  object
 2   Indicador de Abordagem         object
 3   Assinatura do Auto             object
 4   Indicador Veiculo Estrangeiro  object
 5   Sentido Trafego                object
 6   UF Infração                    object
 7   BR Infração                    int64
 8   Km Infração                    int64
 9   Município                      object
 10  Código da Infração             int64
 11  Descrição Abreviada Infração   object
 12  Enquadramento da Infração      object
 13  Início Vigência da Infração    object
 14  Fim Vigência Infração          float64
 15  Medição Infração               object
 16  Descrição Especie Veículo      object
 17  Descrição Marca Veículo        object
 18  Hora Infração                  int64
 19  Medição Considerada            object
 20  Excesso Verificado             object
 21  Qtd Infrações                  int64
dtypes: float64(1), int64(5), object(16)
memory usage: 919.7+ MB
================2025================
<class 'pandas.core.frame.DataFrame'>
Index: 10204474 entries, 0 to 1021815
Data columns (total 25 columns):
 #   Column                         Dtype
---  ------                         -----
 0   Número do Auto                 object
 1   Data da Infração (DD/MM/AAAA)  object
 2   Indicador de Abordagem         object
 3   Assinatura do Auto             object
 4   Sentido Trafego                object
 5   UF Infração                    object
 6   BR Infração                    int64
 7   Km Infração                    int64
 8   Município                      object
 9   Indicador Veiculo Estrangeiro  object
 10  UF Placa                       object
 11  Descrição Especie Veículo      object
 12  Descrição Marca Veículo        object
 13  Descrição Tipo Veículo         object
 14  Descrição Modelo Veiculo       object
 15  Código da Infração             int64
 16  Descrição Abreviada Infração   object
 17  Enquadramento da Infração      object
 18  Início Vigência da Infração    object
 19  Fim Vigência Infração          float64
 20  Medição Infração               object
 21  Hora Infração                  int64
 22  Medição Considerada            float64
 23  Excesso Verificado             float64
 24  Qtd Infrações                  int64
dtypes: float64(3), int64(5), object(17)
memory usage: 2.0+ GB

In [ ]:
for ano in anos_infracoes:
  print(ano.columns.to_list())

['dat_infracao', 'tip_abordagem', 'ind_assinou_auto', 'ind_veiculo_estrangeiro', 'ind_sentido_trafego', 'uf_placa', 'uf_infracao', 'num_br_infracao', 'num_km_infracao', 'nom_municipio', 'cod_infracao', 'descricao_abreviada', 'enquadramento', 'data_inicio_vigencia', 'data_fim_vigencia', 'med_realizada', 'med_considerada', 'exc_verificado', 'especie', 'nome_veiculo_marca', 'nom_modelo_veiculo', 'hora']
['Número do Auto', 'Data da Infração (DD/MM/AAAA)', 'Indicador de Abordagem', 'Assinatura do Auto', 'Indicador Veiculo Estrangeiro', 'Sentido Trafego', 'UF Infração', 'BR Infração', 'Km Infração', 'Município', 'Código da Infração', 'Descrição Abreviada Infração', 'Enquadramento da Infração', 'Início Vigência da Infração', 'Fim Vigência Infração', 'Medição Infração', 'Descrição Especie Veículo', 'Descrição Marca Veículo', 'Hora Infração', 'Medição Considerada', 'Excesso Verificado', 'Qtd Infrações']
['Número do Auto', 'Data da Infração (DD/MM/AAAA)', 'Indicador de Abordagem', 'Assinatura do Auto', 'Sentido Trafego', 'UF Infração', 'BR Infração', 'Km Infração', 'Município', 'Indicador Veiculo Estrangeiro', 'UF Placa', 'Descrição Especie Veículo', 'Descrição Marca Veículo', 'Descrição Tipo Veículo', 'Descrição Modelo Veiculo', 'Código da Infração', 'Descrição Abreviada Infração', 'Enquadramento da Infração', 'Início Vigência da Infração', 'Fim Vigência Infração', 'Medição Infração', 'Hora Infração', 'Medição Considerada', 'Excesso Verificado', 'Qtd Infrações']

In [3]:
map_2018 = {
    "dat_infracao": "Data da Infração (DD/MM/AAAA)",
    "tip_abordagem": "Indicador de Abordagem",
    "ind_assinou_auto": "Assinatura do Auto",
    "ind_veiculo_estrangeiro": "Indicador Veiculo Estrangeiro",
    "ind_sentido_trafego": "Sentido Trafego",
    "uf_placa": "UF Placa",
    "uf_infracao": "UF Infração",
    "num_br_infracao": "BR Infração",
    "num_km_infracao": "Km Infração",
    "nom_municipio": "Município",
    "cod_infracao": "Código da Infração",
    "descricao_abreviada": "Descrição Abreviada Infração",
    "enquadramento": "Enquadramento da Infração",
    "data_inicio_vigencia": "Início Vigência da Infração",
    "data_fim_vigencia": "Fim Vigência Infração",
    "med_realizada": "Medição Infração",
    "med_considerada": "Medição Considerada",
    "exc_verificado": "Excesso Verificado",
    "especie": "Descrição Especie Veículo",
    "nome_veiculo_marca": "Descrição Marca Veículo",
    "nom_modelo_veiculo": "Descrição Modelo Veiculo",
    "hora": "Hora Infração"
}

lista_infracoes_2018 = lista_infracoes_2018.rename(columns=map_2018)

In [6]:
lista_infracoes_2018.head()

,Data da Infração (DD/MM/AAAA),Indicador de Abordagem,Assinatura do Auto,Indicador Veiculo Estrangeiro,Sentido Trafego,UF Placa,UF Infração,BR Infração,Km Infração,Município,...,Enquadramento da Infração,Início Vigência da Infração,Fim Vigência Infração,Medição Infração,Medição Considerada,Excesso Verificado,Descrição Especie Veículo,Descrição Marca Veículo,Descrição Modelo Veiculo,Hora Infração
0,2018-01-01,S,NaN,N,D,GO,GO,153,500,GOIANIA,...,182-V,2016-11-01,NaN,0.0,0.0,0.0,PASSAGEIRO,FIAT,UNO ECONOMY,00:00:00
1,2018-01-01,S,NaN,N,D,GO,GO,153,500,GOIANIA,...,182-V,2016-11-01,NaN,0.0,0.0,0.0,PASSAGEIRO,VW,NOVO VOYAGE TL M,00:00:00
2,2018-01-01,S,NaN,N,D,GO,GO,153,500,GOIANIA,...,182-V,2016-11-01,NaN,0.0,0.0,0.0,PASSAGEIRO,RENAULT,SANDERO EXP1016V,00:00:00
3,2018-01-01,S,NaN,N,D,GO,GO,153,500,GOIANIA,...,182-V,2016-11-01,NaN,0.0,0.0,0.0,PASSAGEIRO,GM,CHEV/SPIN 1.8L A,00:00:00
4,2018-01-01,S,NaN,N,D,GO,GO,153,500,GOIANIA,...,182-V,2016-11-01,NaN,0.0,0.0,0.0,PASSAGEIRO,GM,VECTRA SEDAN ELI,00:00:00

In [ ]:
final_infracao = pd.concat([lista_infracoes_2018,lista_infracoes_2021,lista_infracoes_2025])
#não dá para juntar.

## Acidentes

In [1]:
import os
import zipfile

pastas = [
    "acidentes_2018", "acidentes_2021","acidentes_2025"
]

for pasta in pastas:
    caminho_pasta = f"/content/acidentes/{pasta}"
    arquivo_zip = f"/content/acidentes/{pasta}.zip"

    os.makedirs(caminho_pasta, exist_ok=True)

    with zipfile.ZipFile(arquivo_zip, "r") as dataset:
        dataset.extractall(caminho_pasta)

In [9]:
import pandas as pd

arquivos = [
    "datatran2018.csv", "datatran2021.csv", "datatran2025.csv"
]
lacidentes_final = []
anos = [2018,2021,2025]

for ordem,arquivo in enumerate(arquivos):
      temp = pd.read_csv(f"/content/acidentes/{arquivo}",encoding="latin_1", sep=";")
      lacidentes_final.append(temp)
      print(f"\033[34mDataframe de {anos[ordem]} lido!\033[m")

Dataframe de 2018 lido!
Dataframe de 2021 lido!
Dataframe de 2025 lido!

In [15]:
anos = [2018,2021,2025]

for ordem,ano in enumerate(lacidentes_final):
  print(f"================{anos[ordem]}================")
  ano.info()

================2018================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69333 entries, 0 to 69332
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      69333 non-null  float64
 1   data_inversa            69333 non-null  object
 2   dia_semana              69333 non-null  object
 3   horario                 69333 non-null  object
 4   uf                      69333 non-null  object
 5   br                      69333 non-null  int64
 6   km                      69333 non-null  object
 7   municipio               69333 non-null  object
 8   causa_acidente          69333 non-null  object
 9   tipo_acidente           69310 non-null  object
 10  classificacao_acidente  69332 non-null  object
 11  fase_dia                69333 non-null  object
 12  sentido_via             69333 non-null  object
 13  condicao_metereologica  69333 non-null  object
 14  tipo_pista              69333 non-null  object
 15  tracado_via             69333 non-null  object
 16  uso_solo                69333 non-null  object
 17  pessoas                 69333 non-null  int64
 18  mortos                  69333 non-null  int64
 19  feridos_leves           69333 non-null  int64
 20  feridos_graves          69333 non-null  int64
 21  ilesos                  69333 non-null  int64
 22  ignorados               69333 non-null  int64
 23  feridos                 69333 non-null  int64
 24  veiculos                69333 non-null  int64
 25  latitude                69333 non-null  object
 26  longitude               69333 non-null  object
 27  regional                69333 non-null  object
 28  delegacia               69298 non-null  object
 29  uop                     69291 non-null  object
dtypes: float64(1), int64(9), object(20)
memory usage: 15.9+ MB
================2021================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64567 entries, 0 to 64566
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      64567 non-null  float64
 1   data_inversa            64567 non-null  object
 2   dia_semana              64567 non-null  object
 3   horario                 64567 non-null  object
 4   uf                      64567 non-null  object
 5   br                      64567 non-null  int64
 6   km                      64567 non-null  object
 7   municipio               64567 non-null  object
 8   causa_acidente          64567 non-null  object
 9   tipo_acidente           64567 non-null  object
 10  classificacao_acidente  64566 non-null  object
 11  fase_dia                64567 non-null  object
 12  sentido_via             64567 non-null  object
 13  condicao_metereologica  64567 non-null  object
 14  tipo_pista              64567 non-null  object
 15  tracado_via             64567 non-null  object
 16  uso_solo                64567 non-null  object
 17  pessoas                 64567 non-null  int64
 18  mortos                  64567 non-null  int64
 19  feridos_leves           64567 non-null  int64
 20  feridos_graves          64567 non-null  int64
 21  ilesos                  64567 non-null  int64
 22  ignorados               64567 non-null  int64
 23  feridos                 64567 non-null  int64
 24  veiculos                64567 non-null  int64
 25  latitude                64567 non-null  object
 26  longitude               64567 non-null  object
 27  regional                64567 non-null  object
 28  delegacia               64549 non-null  object
 29  uop                     64531 non-null  object
dtypes: float64(1), int64(9), object(20)
memory usage: 14.8+ MB
================2025================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72529 entries, 0 to 72528
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      72529 non-null  int64
 1   data_inversa            72529 non-null  object
 2   dia_semana              72529 non-null  object
 3   horario                 72529 non-null  object
 4   uf                      72529 non-null  object
 5   br                      72529 non-null  int64
 6   km                      72529 non-null  object
 7   municipio               72529 non-null  object
 8   causa_acidente          72529 non-null  object
 9   tipo_acidente           72529 non-null  object
 10  classificacao_acidente  72528 non-null  object
 11  fase_dia                72529 non-null  object
 12  sentido_via             72529 non-null  object
 13  condicao_metereologica  72529 non-null  object
 14  tipo_pista              72529 non-null  object
 15  tracado_via             72529 non-null  object
 16  uso_solo                72529 non-null  object
 17  pessoas                 72529 non-null  int64
 18  mortos                  72529 non-null  int64
 19  feridos_leves           72529 non-null  int64
 20  feridos_graves          72529 non-null  int64
 21  ilesos                  72529 non-null  int64
 22  ignorados               72529 non-null  int64
 23  feridos                 72529 non-null  int64
 24  veiculos                72529 non-null  int64
 25  latitude                72529 non-null  object
 26  longitude               72529 non-null  object
 27  regional                72527 non-null  object
 28  delegacia               72507 non-null  object
 29  uop                     72491 non-null  object
dtypes: int64(10), object(20)
memory usage: 16.6+ MB

In [19]:
acidentes_final = pd.concat(lacidentes_final,keys=["2018","2021","2025"])
acidentes_final.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 206429 entries, ('2018', np.int64(0)) to ('2025', np.int64(72528))
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      206429 non-null  float64
 1   data_inversa            206429 non-null  object
 2   dia_semana              206429 non-null  object
 3   horario                 206429 non-null  object
 4   uf                      206429 non-null  object
 5   br                      206429 non-null  int64
 6   km                      206429 non-null  object
 7   municipio               206429 non-null  object
 8   causa_acidente          206429 non-null  object
 9   tipo_acidente           206406 non-null  object
 10  classificacao_acidente  206426 non-null  object
 11  fase_dia                206429 non-null  object
 12  sentido_via             206429 non-null  object
 13  condicao_metereologica  206429 non-null  object
 14  tipo_pista              206429 non-null  object
 15  tracado_via             206429 non-null  object
 16  uso_solo                206429 non-null  object
 17  pessoas                 206429 non-null  int64
 18  mortos                  206429 non-null  int64
 19  feridos_leves           206429 non-null  int64
 20  feridos_graves          206429 non-null  int64
 21  ilesos                  206429 non-null  int64
 22  ignorados               206429 non-null  int64
 23  feridos                 206429 non-null  int64
 24  veiculos                206429 non-null  int64
 25  latitude                206429 non-null  object
 26  longitude               206429 non-null  object
 27  regional                206427 non-null  object
 28  delegacia               206354 non-null  object
 29  uop                     206313 non-null  object
dtypes: float64(1), int64(9), object(20)
memory usage: 50.8+ MB

In [20]:
acidentes_final.head()

              id data_inversa     dia_semana   horario  uf   br     km  \
2018 0  100027.0   2018-01-01  segunda-feira  06:00:00  TO  153  393,1
     1  100044.0   2018-01-01  segunda-feira  08:30:00  SE  101  123,4
     2  100046.0   2018-01-01  segunda-feira  08:50:00  TO  153    347
     3  100052.0   2018-01-01  segunda-feira  05:30:00  PA  155    221
     4  100053.0   2018-01-01  segunda-feira  10:25:00  BA  116  289,6

                  municipio                      causa_acidente  \
2018 0         RIO DOS BOIS         Falta de Atenção à Condução
     1    ITAPORANGA DAJUDA  Não guardar distância de segurança
     2               GUARAI         Falta de Atenção à Condução
     3  ELDORADO DO CARAJAS                  Ingestão de Álcool
     4               TUCANO              Ultrapassagem Indevida

                    tipo_acidente  ... feridos_graves ilesos ignorados  \
2018 0            Colisão frontal  ...              1      1         0
     1           Colisão traseira  ...              0      2         0
     2            Colisão lateral  ...              0      2         1
     3            Colisão lateral  ...              0      1         0
     4  Saída de leito carroçável  ...              1      0         1

       feridos veiculos      latitude     longitude  regional  delegacia  \
2018 0       1        2   -9,35641407  -48,54610294   SPRF-TO   DEL02-TO
     1       0        2  -11,04476007     -37,36498   SPRF-SE   DEL02-SE
     2       0        3     -8,952295    -48,500107   SPRF-TO   DEL02-TO
     3       0        2     -6,345512    -49,389626   SPRF-PA   DEL03-PA
     4       1        2  -11,08661652  -38,83420181   SPRF-BA   DEL02-BA

                     uop
2018 0    UOP02-DEL02-TO
     1    UOP01-DEL02-SE
     2    UOP02-DEL02-TO
     3    UOP01-DEL03-PA
     4  DEL10/2-UOP02/BA

[5 rows x 30 columns]

### Verificando Nulos e duplicatas.

In [24]:
acidentes_final.isnull().sum()

id                          0
data_inversa                0
dia_semana                  0
horario                     0
uf                          0
br                          0
km                          0
municipio                   0
causa_acidente              0
tipo_acidente              23
classificacao_acidente      3
fase_dia                    0
sentido_via                 0
condicao_metereologica      0
tipo_pista                  0
tracado_via                 0
uso_solo                    0
pessoas                     0
mortos                      0
feridos_leves               0
feridos_graves              0
ilesos                      0
ignorados                   0
feridos                     0
veiculos                    0
latitude                    0
longitude                   0
regional                    2
delegacia                  75
uop                       116
dtype: int64

In [25]:
acidentes_final.duplicated().sum()

np.int64(0)

### Alterando variáveis.

In [26]:
acidentes_final["km"].unique()

array(['393,1', '123,4', '347', ..., '796,8', '1107', '691,4'],
      dtype=object)

In [29]:
acidentes_final["km"] = (acidentes_final["km"].str.replace(",", ".").astype(float))

In [27]:
acidentes_final["latitude"].unique()

array(['-9,35641407', '-11,04476007', '-8,952295', ..., '-8,25368',
       '-26,99305955', '-19,298811'], dtype=object)

In [30]:
acidentes_final["latitude"] = (acidentes_final["latitude"].str.replace(",", ".").astype(float))

In [28]:
acidentes_final["longitude"].unique()

array(['-48,54610294', '-37,36498', '-48,500107', ..., '-35,97546',
       '-48,6609548', '-42,371921'], dtype=object)

In [31]:
acidentes_final["longitude"] = (acidentes_final["longitude"].str.replace(",", ".").astype(float))

In [32]:
acidentes_final["data_inversa"] = pd.to_datetime(acidentes_final["data_inversa"],errors="coerce")

In [33]:
acidentes_final["horario"] = pd.to_datetime(acidentes_final["horario"],format="%H:%M:%S",errors="coerce").dt.time

In [36]:
categoricas = acidentes_final.select_dtypes(include="object").columns

for col in categoricas:
    acidentes_final[col] = acidentes_final[col].astype("category")

In [37]:
acidentes_final.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 206429 entries, ('2018', np.int64(0)) to ('2025', np.int64(72528))
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      206429 non-null  float64
 1   data_inversa            206429 non-null  datetime64[ns]
 2   dia_semana              206429 non-null  category
 3   horario                 206429 non-null  category
 4   uf                      206429 non-null  category
 5   br                      206429 non-null  int64
 6   km                      206429 non-null  float64
 7   municipio               206429 non-null  category
 8   causa_acidente          206429 non-null  category
 9   tipo_acidente           206406 non-null  category
 10  classificacao_acidente  206426 non-null  category
 11  fase_dia                206429 non-null  category
 12  sentido_via             206429 non-null  category
 13  condicao_metereologica  206429 non-null  category
 14  tipo_pista              206429 non-null  category
 15  tracado_via             206429 non-null  category
 16  uso_solo                206429 non-null  category
 17  pessoas                 206429 non-null  int64
 18  mortos                  206429 non-null  int64
 19  feridos_leves           206429 non-null  int64
 20  feridos_graves          206429 non-null  int64
 21  ilesos                  206429 non-null  int64
 22  ignorados               206429 non-null  int64
 23  feridos                 206429 non-null  int64
 24  veiculos                206429 non-null  int64
 25  latitude                206429 non-null  float64
 26  longitude               206429 non-null  float64
 27  regional                206427 non-null  category
 28  delegacia               206354 non-null  category
 29  uop                     206313 non-null  category
dtypes: category(16), datetime64[ns](1), float64(4), int64(9)
memory usage: 29.9+ MB

### Procurando codificação

In [40]:
acidentes_final.iloc[0]

id                                           100027.0
data_inversa                      2018-01-01 00:00:00
dia_semana                              segunda-feira
horario                                      06:00:00
uf                                                 TO
br                                                153
km                                              393.1
municipio                                RIO DOS BOIS
causa_acidente            Falta de Atenção à Condução
tipo_acidente                         Colisão frontal
classificacao_acidente            Com Vítimas Feridas
fase_dia                                    Pleno dia
sentido_via                               Decrescente
condicao_metereologica                      Céu Claro
tipo_pista                                    Simples
tracado_via                                    Aclive
uso_solo                                          Não
pessoas                                             2
mortos                                              0
feridos_leves                                       0
feridos_graves                                      1
ilesos                                              1
ignorados                                           0
feridos                                             1
veiculos                                            2
latitude                                    -9.356414
longitude                                  -48.546103
regional                                      SPRF-TO
delegacia                                    DEL02-TO
uop                                    UOP02-DEL02-TO
Name: (2018, 0), dtype: object

### Não há codificação.