# AED - Análise Explorátoria de Dados

## Tabulação Cruzada

<div class="alert alert-danger">
     
**AVISO!**
 
Titulos clicáveis estão em **negrito** basta clicar na seta.
     
</div>

In [2]:
import pandas as pd

data = {'speaker':["upsy-daisy",  "upsy-daisy",  "upsy-daisy",  "upsy-daisy",  "tombliboo",   "tombliboo",   "makka-pakka", "makka-pakka",
  "makka-pakka", "makka-pakka"],
       'utterance':["pip", "pip", "onk", "onk", "ee",  "oo",  "pip", "pip", "onk", "onk"]}

df = pd.DataFrame(data, columns=['speaker','utterance'])

df

       speaker utterance
0   upsy-daisy       pip
1   upsy-daisy       pip
2   upsy-daisy       onk
3   upsy-daisy       onk
4    tombliboo        ee
5    tombliboo        oo
6  makka-pakka       pip
7  makka-pakka       pip
8  makka-pakka       onk
9  makka-pakka       onk

<details>
  <summary>
    <font size='5', color='green'>
      <b>7.2 Tabulação e Tabela Cruzada</b>
    </font>
  </summary>
 
- Contar frequências ou cruzar variáveis usando pd.crosstab( ).

 * Simples
```python
            pd.crosstab(index=df["speaker"], columns="count")
            #número de falas por personagem.
```
 * Tabela cruzada 
 ```python
            pd.crosstab(index=df["speaker"], columns=df["utterance"], margins=True)
 ```
</details>

In [3]:
pd.crosstab(index=df["speaker"], columns="count")

col_0        count
speaker
makka-pakka      4
tombliboo        2
upsy-daisy       4

In [4]:
pd.crosstab(index=df["speaker"], columns=df["utterance"], margins=True)

utterance    ee  onk  oo  pip  All
speaker
makka-pakka   0    2   0    2    4
tombliboo     1    0   1    0    2
upsy-daisy    0    2   0    2    4
All           1    4   1    4   10

<details>
  <summary>
    <font size='5', color='green'>
      <b>7.2.1 Convertendo contagens em proporções</b>
    </font>
  </summary>
 
- Salvar e renomear totais
```python
            tabs = pd.crosstab(index=df["speaker"], columns=df["utterance"],margins=True)

            tabs.columns = list(tabs.columns)[0:-1] + ['rowtotals'] #"All" vira 'rowtotals' por coluna
            tabs.index = list(tabs.index)[0:-1] + ['coltotals'] #"All" vira 'coltotals' por linha
```
- Proporção por coluna
```python
            tabs / tabs.loc['coltotals']
            # vai dividir todo tabs por coltotals
```
- Proporção por linha
```python
            tabs.div(tabs["rowtotals"], axis=0)
            # vai dividir todo tabs por rowtotals
```
</details>

In [5]:
tabs = pd.crosstab(index=df["speaker"], columns=df["utterance"],margins=True)

tabs.columns = list(tabs.columns)[0:-1] + ['rowtotals']
tabs.index = list(tabs.index)[0:-1] + ['coltotals']

tabs

             ee  onk  oo  pip  rowtotals
makka-pakka   0    2   0    2          4
tombliboo     1    0   1    0          2
upsy-daisy    0    2   0    2          4
coltotals     1    4   1    4         10

In [6]:
tabs / tabs.loc['coltotals']

              ee  onk   oo  pip  rowtotals
makka-pakka  0.0  0.5  0.0  0.5        0.4
tombliboo    1.0  0.0  1.0  0.0        0.2
upsy-daisy   0.0  0.5  0.0  0.5        0.4
coltotals    1.0  1.0  1.0  1.0        1.0

In [7]:
tabs.div(tabs["rowtotals"], axis=0)

              ee  onk   oo  pip  rowtotals
makka-pakka  0.0  0.5  0.0  0.5        1.0
tombliboo    0.5  0.0  0.5  0.0        1.0
upsy-daisy   0.0  0.5  0.0  0.5        1.0
coltotals    0.1  0.4  0.1  0.4        1.0

<details>
  <summary>
    <font size='5', color='green'>
      <b>7.3 Transformação e recodificação de variáveis</b>
    </font>
  </summary>
 
- As vezes é preciso transformar e reclassificar os dados, pois 
nem sempre estão no formato ideal.
- 7.3.1 Criando variáveis transformadas
  * Pegar um dado original e aplicar uma função matemática nele para criar uma nova versão mais útil.
  * O sistema fuciona como se fosse uma questão de opinião forte,neutra ou fraca.
  ```python
      data = [1, 7, 3, 4, 4, 4, 2, 6, 5, 5]
      # 1 - Opinião Fraca
      # 4 - Opinião Neutra
      # 7 - Opinião Forte
      data = [x-4 for x in data]
      # Após o código fica mais obvio
      [-3,  3, -1,  0,  0,  0, -2,  2,  1,  1]
      # Negativos: Fraco
      # 0 Neutro
      # Positivos: Forte
      
      #Usando
      data = np.sign(data)
      [-1,  1, -1,  0,  0,  0, -1,  1,  1,  1]
      # Fica ainda melhor de observar
      # -1 Fraco
      # 0 Neutro
      # 1 Forte
  ```
  * Força de Opinião
  ```python
      df['centered'] = df['scores']-4 # Transforma em opinião
      df['opinion_strength'] = abs(df['centered']) # O Nível de força da opinião
      df['opinion_direction'] = np.sign(df['scores']-4) # Exemplifica opinião positiva, negativa e neutra.
  ```
</details>

In [11]:
data = [1, 7, 3, 4, 4, 4, 2, 6, 5, 5]
data = [x-4 for x in data]
data

[-3, 3, -1, 0, 0, 0, -2, 2, 1, 1]

In [12]:
import numpy as np
data = np.array([1, 7, 3, 4, 4, 4, 2, 6, 5, 5])
data = data - 4
data

array([-3,  3, -1,  0,  0,  0, -2,  2,  1,  1])

In [13]:
data = np.array([1, 7, 3, 4, 4, 4, 2, 6, 5, 5])
data = data - 4
data = np.sign(data)
data

array([-1,  1, -1,  0,  0,  0, -1,  1,  1,  1])

In [14]:
df = pd.DataFrame(
    {'scores': np.array([1, 7, 3, 4, 4, 4, 2, 6, 5, 5])
    })

df

   scores
0       1
1       7
2       3
3       4
4       4
5       4
6       2
7       6
8       5
9       5

In [15]:
df['centered'] = df['scores']-4
df['opinion_strength'] = abs(df['centered'])
df['opinion_direction'] = np.sign(df['scores']-4)
df

   scores  centered  opinion_strength  opinion_direction
0       1        -3                 3                 -1
1       7         3                 3                  1
2       3        -1                 1                 -1
3       4         0                 0                  0
4       4         0                 0                  0
5       4         0                 0                  0
6       2        -2                 2                 -1
7       6         2                 2                  1
8       5         1                 1                  1
9       5         1                 1                  1

<details>
  <summary>
    <font size='5', color='green'>
      <b>7.3.2 Transformar números em categorias</b>
    </font>
  </summary>

- Usando cut você pode definir intervalos e transformar em categorias. 
```python
            df['categories'] = pd.cut(x = df['age'], bins = [0,20,40,60], labels = ['young', 'adult', 'older'])
            # O objetivo é transformar idade em grupos.
            # 0–20 -> jovem
            # 21–40 -> adulto
            # 41–60 -> mais velho
```
- Cortando em intervalos iguais ele é automatico.
```python
            pd.cut(df['age'], bins=3)
            # divide em intervalos iguais em tamanho
```
- Quantidade de elementos equilibradas
```python
            pd.qcut(df['age'], q=[0, .33, .66, 1])
            # Divide em grupos com mesma quantidade de dados percentuais
```

</details>

In [16]:
age = [60,58,24,26,34,42,31,30,33,2,9]
df = pd.DataFrame(
    {'age': np.array([60,58,24,26,34,42,31,30,33,2,9])
    })

df

    age
0    60
1    58
2    24
3    26
4    34
5    42
6    31
7    30
8    33
9     2
10    9

In [18]:
df['categories'] = pd.cut(x = df['age'], bins = [0,20,40,60], labels = ['young', 'adult', 'older'])
df

    age categories
0    60      older
1    58      older
2    24      adult
3    26      adult
4    34      adult
5    42      older
6    31      adult
7    30      adult
8    33      adult
9     2      young
10    9      young

In [19]:
pd.cut(df['age'], bins=3)

0       (40.667, 60.0]
1       (40.667, 60.0]
2     (21.333, 40.667]
3     (21.333, 40.667]
4     (21.333, 40.667]
5       (40.667, 60.0]
6     (21.333, 40.667]
7     (21.333, 40.667]
8     (21.333, 40.667]
9      (1.942, 21.333]
10     (1.942, 21.333]
Name: age, dtype: category
Categories (3, interval[float64, right]): [(1.942, 21.333] < (21.333, 40.667] < (40.667, 60.0]]

In [20]:
pd.qcut(df['age'], q=[0, .33, .66, 1])

0      (33.6, 60.0]
1      (33.6, 60.0]
2     (1.999, 27.2]
3     (1.999, 27.2]
4      (33.6, 60.0]
5      (33.6, 60.0]
6      (27.2, 33.6]
7      (27.2, 33.6]
8      (27.2, 33.6]
9     (1.999, 27.2]
10    (1.999, 27.2]
Name: age, dtype: category
Categories (3, interval[float64, right]): [(1.999, 27.2] < (27.2, 33.6] < (33.6, 60.0]]